export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_BOOKS_PENDING = 'REQUEST_BOOKS_PENDING';
export const REQUEST_BOOKS_SUCCESS = 'REQUEST_BOOKS_SUCCESS';
export const REQUEST_BOOKS_FAILED = 'REQUEST_BOOKS_FAILED';

export const REQUEST_ONE_BOOKS_PENDING = 'REQUEST_ONE_BOOKS_PENDING';
export const REQUEST_ONE_BOOKS_SUCCESS = 'REQUEST_ONE_BOOKS_SUCCESS';
export const REQUEST_ONE_BOOKS_FAILED = 'REQUEST_ONE_BOOKS_FAILED';

export const POST_BOOKS_PENDING = 'POST_BOOKS_PENDING';
export const POST_BOOKS_SUCCESS = 'POST_BOOKS_SUCCESS';
export const POST_BOOKS_FAILED = 'POST_BOOKS_FAILED';

export const PUT_BOOKS_PENDING = 'PUT_BOOKS_PENDING';
export const PUT_BOOKS_SUCCESS = 'PUT_BOOKS_SUCCESS';
export const PUT_BOOKS_FAILED = 'PUT_BOOKS_FAILED';

export const DELETE_BOOKS_PENDING = 'DELETE_BOOKS_PENDING';
export const DELETE_BOOKS_SUCCESS = 'DELETE_BOOKS_SUCCESS';
export const DELETE_BOOKS_FAILED = 'DELETE_BOOKS_FAILED';